config/routes.rb
Rails.application.routes.draw do
  # Defines the root path route ("/")
  root "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: { confirmations: 'users/confirmations', registrations: 'users/registrations' }

  resources :birthday_buddies, except: [:new, :show]
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/birthday_buddy.rb
# == Schema Information
#
# Table name: birthday_buddies
#
#  id                                   :integer          not null, primary key
#  first_name                           :string           default(""), not null
#  gregorian_birthday                   :date             not null
#  last_name                            :string           default("")
#  upcoming_gregorian_birthday          :date             not null
#  upcoming_hijri_birthday_in_gregorian :date             not null
#  created_at                           :datetime         not null
#  updated_at                           :datetime         not null
#  user_id                              :integer          not null
#
# Indexes
#
#  index_birthday_buddies_on_user_id  (user_id)
#
# Foreign Keys
#
#  user_id  (user_id => users.id)
#
class BirthdayBuddy < ApplicationRecord
  # * Associations
  belongs_to :user, touch: true

  #  * name_of_person
  include HasPersonName

  # * Validations
  validates_presence_of :first_name, :gregorian_birthday
  validate :gregorian_birthday_cannot_be_in_future, if: :will_save_change_to_gregorian_birthday?

  # * Callbacks
  before_save :set_upcoming_gregorian_birthday, if: :will_save_change_to_gregorian_birthday?
  before_save :set_upcoming_hijri_birthday_in_gregorian, if: :will_save_change_to_gregorian_birthday?
  # birthday reminders
  after_save :set_happy_gregorian_birthday_reminder_email, if: :saved_change_to_upcoming_gregorian_birthday?
  after_save :set_happy_hijri_birthday_reminder_email, if: :saved_change_to_upcoming_hijri_birthday_in_gregorian?

  # * Helper Methods
  include HijriHelpers

  def hijri_birthday
    hijri_date_of(gregorian_birthday)
  end

  def upcoming_hijri_birthday
    create_future_hijri_birthdate(hijri_birthday)
  end

  private

  # callbacks
  def set_upcoming_gregorian_birthday
    birthday = gregorian_birthday.change(year: Date.today.year)
    self.upcoming_gregorian_birthday =  birthday.future? ? birthday : birthday.next_year
  end

  def set_upcoming_hijri_birthday_in_gregorian
    self.upcoming_hijri_birthday_in_gregorian = gregorian_date_of(upcoming_hijri_birthday)
  end

  def set_happy_gregorian_birthday_reminder_email
    their_birthday_day = upcoming_gregorian_birthday.in_time_zone(user.time_zone).midnight

    # send birthday notification email to user on midnight of their time zone
    WishHappyGregorianBirthdayJob.set(wait_until: their_birthday_day).perform_later(self.user, self)
  end

  def set_happy_hijri_birthday_reminder_email
    their_birthday_day =  upcoming_hijri_birthday_in_gregorian.in_time_zone(user.time_zone).midnight

    # send birthday notification email to user on midnight of their time zone
    WishHappyHijriBirthdayJob.set(wait_until: their_birthday_day).perform_later(self.user, self)
  end

  # * Custom Validation Methods
  def gregorian_birthday_cannot_be_in_future
    errors.add(:gregorian_birthday, "cannot be in future") if gregorian_birthday.future?
  end
end

app/controllers/birthday_buddies_controller.rb
class BirthdayBuddiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_birthday_buddy, only: %i(edit update destroy)

  def index
    @birthday_buddies = current_user.birthday_buddies.order(:upcoming_gregorian_birthday)
    @birthday_buddy = BirthdayBuddy.new
  end

  def create
    @birthday_buddy = current_user.birthday_buddies.new(birthday_buddy_params)

    respond_to do |format|
      if @birthday_buddy.save
        format.html { redirect_to birthday_buddies_path, notice: "Birthdate created" }
      else
        @birthday_buddies = current_user.birthday_buddies.order(:upcoming_gregorian_birthday)
        format.html { render :index, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @birthday_buddy.update(birthday_buddy_params)
        format.html { redirect_to birthday_buddies_path, notice: "Details Updated!" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @birthday_buddy.destroy
    redirect_to birthday_buddies_path, notice: "Birthday Deleted!"
  end

  private
  def birthday_buddy_params
    params.require(:birthday_buddy).permit(:name, :gregorian_birthday)
  end

  def set_birthday_buddy
    @birthday_buddy = BirthdayBuddy.find(params[:id])
  end
end

app/views/birthday_buddies/_birthday_buddy.html.erb
<turbo-frame id="<%= dom_id birthday_buddy %>" target= '_top'  class="flex justify-between items-center gap-4 md:gap-8">
  <%# Full Name %>
  <p class="w-full flex items-center justify-between gap-1">
    <span class="w-7/12 text-lg md:text-xl tracking-wider text-secondary-900 dark:text-secondary-200">
      <%= birthday_buddy.name.possessive %>
    </span>
    <span class="font-light dark:font-extralight italic text-sm md:text-base text-secondary-700 dark:text-secondary-400">
      In <%= distance_of_gregorian_birthday_in_words(birthday_buddy) %>
    </span>
  </p>

  <%# Show Modal %>
  <div>
    <button
      data-modal-toggle="<%= dom_id(birthday_buddy, "show") %>"
      data-action= "click->dialog#openShowModal"
      class="form-submit w-auto px-3 py-1.5 md:px-5"
    >
    Show
    </button>
  </div>

  <%= render "show_dialog", birthday_buddy: birthday_buddy %>
</turbo-frame>

app/views/birthday_buddies/_form.html.erb
<h1 class="font-semibold dark:font-medium text-2xl md:text-3xl text-center tracking-wide bg-gradient-text-clip mb-5 md:mb-8">Add birthday buddy</h1>

<%# Validation Error Messages %>
<%= render "devise/shared/error_messages", resource: @birthday_buddy %>

<%# Form %>
<%= form_with( model: buddy, data: { controller: "flatpickr"}, class: "grid gap-5" ) do |f| %>

  <%# first_name & last_name field %>
  <%= f.text_field :name, placeholder: "Full Name", class: "form-input" %>

  <div class="flex gap-5">
    <%# gregorian_birthday %>
    <%= f.date_field :gregorian_birthday, placeholder: "Date Of Birth",  class: "form-input gregorian-date" %>

    <%# Submit %>
    <%= f.submit "Create", data: {turbo_submits_with: "Creating..."}, class: "form-submit w-auto py-2 px-4 md:px-5" %>
  </div>
<% end %>

app/views/birthday_buddies/_show_dialog.html.erb
<dialog id="<%= dom_id(birthday_buddy, "show") %>" data-turbo-temporary class="z-40 w-3/4 sm:w-1/2 lg:max-w-md xl:max-w-lg dark:bg-gray-800 bg-primary-100 border-2 border-primary-400 dark:border-secondary-500 rounded-lg shadow backdrop:backdrop-blur-sm space-y-5 md:space-y-6 lg:space-y-7 p-5 sm:p-6 md:p-7">
  <%# Header %>
  <div class="flex justify-between mb-4 rounded-t sm:mb-5">
    <%# Heading %>
    <hgroup class="text-xl md:text-2xl lg:text-3xl text-primary-900 dark:text-primary-100">
      <h3 class="font-semibold ">
        <%=  birthday_buddy.first_name %>
      </h3>
      <h4>
        <%=  birthday_buddy.last_name %>
      </h4>
    </hgroup>

    <!-- Close Button-->
    <button data-action="click->dialog#closeShowModal" data-modal-toggle="<%= dom_id(birthday_buddy, "show") %>" class="text-primary-700 absolute top-2.5 right-2.5 bg-transparent hover:bg-primary-200 hover:text-primary-950 rounded-lg p-1.5 ml-auto inline-flex items-center dark:hover:bg-primary-600 dark:hover:text-primary-200">
      <%= render "shared/svg/x_mark", classes: "size-5 sm:size-6 md:size-7" %>
    </button>
  </div>

  <hr class="divider w-3/4">

  <%# Other details %>
  <dl class="space-y-7">
    <div class="space-y-1">
      <div class="flex gap-2 items-end lg:items-center justify-between">
        <dt class="text-lg md:text-xl lg:text-2xl font-semibold tracking-wide leading-6 text-secondary-900 dark:text-secondary-300">🎁&nbsp;Next Birthday</dt>
        <span class="font-extralight italic text-sm text-secondary-600 dark:text-secondary-300/80">
          In <%= distance_of_gregorian_birthday_in_words(birthday_buddy) %>
        </span>
      </div>
      <dd class="text-base md:text-lg lg:text-xl font-medium text-secondary-600 dark:text-secondary-300/80">
        🗓️&nbsp;&nbsp;<%= readable_date(birthday_buddy.upcoming_gregorian_birthday) %>
      </dd>
    </div>
    <div class="space-y-1">
      <div class="flex gap-2 items-end lg:items-center justify-between">
        <dt class="text-lg md:text-xl lg:text-2xl font-semibold tracking-wide leading-6 text-secondary-900 dark:text-secondary-300">🎁&nbsp;Next Waras</dt>
        <span class="font-extralight italic text-sm text-secondary-600 dark:text-secondary-300/80">
          In <%= distance_of_hijri_birthday_in_words(birthday_buddy) %>
        </span>
      </div>
      <dd class="text-base md:text-lg lg:text-xl font-medium text-secondary-600 dark:text-secondary-300/80">
        🗓️&nbsp;&nbsp;<%= readable_date(birthday_buddy.upcoming_hijri_birthday) %>
      </dd>
    </div>
    <div class="space-y-1">
      <dt class="text-base md:text-lg lg:text-xl font-semibold tracking-wide leading-6 text-secondary-900 dark:text-secondary-300">👶&nbsp;Date of Birth</dt>
      <dd class="mb-4 sm:mb-5 text-sm md:text-base lg:text-lg font-light text-secondary-600 dark:text-secondary-300/80">
        🗓️&nbsp;&nbsp;<%= readable_date(birthday_buddy.gregorian_birthday) %>
        &nbsp;(<%= readable_date(birthday_buddy.hijri_birthday) %>)
      </dd>
    </div>
  </dl>

  <hr class="divider w-3/4">

  <%# birthday reminder note %>
  <div class="flex gap-x-1.5 lg:gap-x-2.5 items-center text-secondary-800/85 md:text-secondary-800/80 dark:text-secondary-200/50">
    <%= render "shared/svg/envelope" %>
    <p class= "text-xs md:text-sm font-extralight md:font-light leading-4 italic tracking-wider md:tracking-wide">Reminders will be sent at midnight for both birthdays.</p>
  </div>

  <%# Action %>
  <div class="flex justify-evenly">
    <button data-action="click->dialog#closeShowModal" data-modal-toggle="<%= dom_id(birthday_buddy, "show") %>"  class="py-1.5 sm:py-2 px-4 md:px-5 lg:py-2.5 text-lg md:text-xl font-medium rounded-lg border focus:ring-4 focus:outline-none  focus:z-10 focus:ring-primary-300 text-seconadry-700 bg-secondary-300 hover:bg-secondary-400 border-secondary-200 dark:bg-gray-700 dark:text-primary-100 dark:border-secondary-500 dark:hover:text-primary-50 dark:hover:bg-gray-600 dark:focus:ring-gray-600">
      Close
    </button>
    <%#  Edit %>
    <%= link_to "Edit", edit_birthday_buddy_path(birthday_buddy), class:"form-submit w-auto py-1.5 sm:py-2 lg:py-2.5 md:px-6" %>
  </div>
</dialog>

app/views/birthday_buddies/edit.html.erb
<%# Form %>
<section class="form-page">
  <div class="form-layout">

    <%# Heading %>
    <h1 class="form-header">Update Birthday Buddy</h1>

    <%= form_with(model: @birthday_buddy, data: { controller: "flatpickr"}) do |f| %>
      <div class="space-y-4 md:space-y-6">

        <%# Validation Error Messages %>
        <%= render "devise/shared/error_messages", resource: @birthday_buddy %>

        <%# First Name & Last Name %>
        <div class="field">
          <%= f.label :name, class: "form-label" %>
          <%= f.text_field :name, class: "form-input" %>
        </div>

        <%# Gregorian Birthday %>
        <div class="field">
          <%= f.label :gregorian_birthday, class: "form-label" %>
          <%= f.date_field :gregorian_birthday, class: "form-input gregorian-date" %>
        </div>

        <%# Submit %>
        <div class="actions">
          <%= f.submit "Update", data: {turbo_submits_with: "Updating..."}, class: "form-submit" %>
        </div>
      </div>
    <% end %>

    <%# Back %>
    <%= render "shared/back" %>

    <%# divider %>
    <hr class="divider">

    <%# Cancel Account %>
    <div data-controller="dialog" class="flex justify-center">
      <button
        data-action="click->dialog#open"
        class= "form-submit-danger"
      >Delete Birthday Buddy</button>

      <%= render "/shared/destroy_dialog", destroy_path: birthday_buddy_path(@birthday_buddy), message: "Are you sure you want to delete your birthday buddy?" %>
    </div>
  </div>
</section>

app/views/birthday_buddies/index.html.erb
<section class="grid w-full sm:w-3/4 md:max-w-md lg:max-w-lg rounded-xl border-4 border-primary-500 dark:border-primary-700 bg-secondary-50 dark:bg-gray-900 p-5 md:p-8 lg:px-12 mt-8">
  <%# New birthday_buddy form %>
  <%= render "form", buddy: @birthday_buddy %>
</section>

<%# divider %>
<hr class="divider">

<%# Birthdays %>
<% if @birthday_buddies.present? %>
  <article data-controller="dialog" class= "w-full sm:max-w-md lg:max-w-lg grid justify-items-stretch gap-8 md:gap-14 mb-16 md:mb-10">
    <h2 class="text-balance font-semibold text-2xl md:text-3xl tracking-wide text-center text-primary-950 dark:text-primary-100">🎂&nbsp;&nbsp;Upcoming birthdays! &nbsp;&nbsp;🎉</h2>

    <%= turbo_stream_from current_user %>
    <div id="birthday_buddies" class="grid gap-8 md:gap-12">
      <%= render @birthday_buddies %>
    </div>
  </article>
<% end %>